#!/usr/bin/env bash

# Keep track of the devstack directory
TOP_DIR=$(cd $(dirname "$0") && pwd)

# Import common functions
source $TOP_DIR/functions

GLANCE_HOSTPORT=127.0.0.1:9292
#IMAGE_NAME=cirros-0.3.0-x86_64-hadi

#KERNEL=/home/savi/newimage/cirros-0.3.0-x86_64-vmlinuz
#RAMDISK=/home/savi/newimage/cirros-0.3.0-x86_64-initrd
#IMAGE=/home/savi/newimage/cirros-0.3.0-x86_64-blank.img

IMAGE_NAME=savi-fpga-image-adder
IMAGE=/home/savi/devstack/fpga_image_adder

TOKEN=$(keystone  token-get | grep ' id ' | get_field 2)
KERNEL_ID=""; RAMDISK_ID="";
#if [ -n "$KERNEL" ]; then
#    KERNEL_ID=$(glance --os-auth-token $TOKEN --os-image-url http://$GLANCE_HOSTPORT image-create --name "$IMAGE_NAME-kernel" --public --container-format aki --disk-format aki < "$KERNEL" | grep ' id ' | get_field 2)
#fi
#if [ -n "$RAMDISK" ]; then
#   RAMDISK_ID=$(glance --os-auth-token $TOKEN --os-image-url http://$GLANCE_HOSTPORT image-create --name "$IMAGE_NAME-ramdisk" --public --container-format ari --disk-format ari < "$RAMDISK" | grep ' id ' | get_field 2)
#fi
#glance --os-auth-token $TOKEN --os-image-url http://$GLANCE_HOSTPORT image-create --name "${IMAGE_NAME%.img}" --public --container-format ami --disk-format ami ${KERNEL_ID:+--property kernel_id=$KERNEL_ID} ${RAMDISK_ID:+--property ramdisk_id=$RAMDISK_ID} < "${IMAGE}"
glance --os-auth-token $TOKEN --os-image-url http://$GLANCE_HOSTPORT image-create --name "${IMAGE_NAME}" --public --container-format bare --disk-format raw < "${IMAGE}"
